- name: Demo on Play Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}

- name: Demo on Task Variables
  hosts: all
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com

- name: Demo on CLI Variables
  hosts: all
  tasks:
    - name: Print URL1 var from CLI
      debug:
        msg: URL1 = {{ URL1 }}
