- name: Update SystemD script for {{ APP }} Service
  ansible.builtin.replace:
    path: /home/roboshop/{{APP}}/systemd.service
    regexp: "{{item.source}}"
    replace: "{{item.dest}}"
  loop:
    - {source: "MONGO_DNSNAME", dest: "mongodb-{{ENV}}.devopsb54.tk"}
    - {source: "MONGO_ENDPOINT", dest: "mongodb-{{ENV}}.devopsb54.tk"}
    - {source: "REDIS_ENDPOINT", dest: "redis-{{ENV}}.devopsb54.tk"}
    - {source: "CATALOGUE_ENDPOINT", dest: "catalogue-{{ENV}}.devopsb54.tk"}
    - {source: "CARTHOST", dest: "cart-{{ENV}}.devopsb54.tk"}
    - {source: "USERHOST", dest: "user-{{ENV}}.devopsb54.tk"}
    - {source: "AMQPHOST", dest: "rabbitmq-{{ENV}}.devopsb54.tk"}
    - {source: "CARTENDPOINT", dest: "cart-{{ENV}}.devopsb54.tk"}
    - {source: "DBHOST", dest: "mysql-{{ENV}}.devopsb54.tk"}

- name: Setup SystemD script
  ansible.builtin.shell: mv /home/roboshop/{{APP}}/systemd.service /etc/systemd/system/{{APP}}.service

- name: Start {{APP}} Service
  ansible.builtin.systemd:
    name: {{APP}}
    state: restarted
    enabled: yes
    daemon_reload: yes
